### ISSUE TITLE
Rough expansion of social icons

### ISSUE THREAD

**Issue by 22a** [DUCSS/ducss-site#46]
![jagged](https://cloud.githubusercontent.com/assets/7144173/12697857/143ce93c-c785-11e5-9b4e-34dd17259c89.gif)

Caused by manually scaling image from 60px to 64px:
https://github.com/DUCSS/ducss-site/blob/master/app/assets/stylesheets/footer.scss#L41

as opposed to using webkit transform scale with a easing transition such as:

``` scss
%smooth {
  -webkit-transition: all 0.3s ease-in-out;
  -moz-transition: all 0.3s ease-in-out;
  -o-transition: all 0.3s ease-in-out;
  -ms-transition: all 0.3s ease-in-out;
  transition: all 0.3s ease-in-out;
}

%expand-on-hover {
  &:hover {
    -webkit-transform: scale(1.1);
    -moz-transform: scale(1.1);
    -o-transform: scale(1.1);
    transform: scale(1.1);
  }
}
```
